/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.5.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QLocale>
#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QDockWidget>
#include <QtWidgets/QGraphicsView>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTextBrowser>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QVBoxLayout>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QAction *actionLexize;
    QAction *actionParse;
    QAction *actionEvaluate;
    QAction *actionKalimatManual;
    QAction *action_walkthroughs;
    QAction *action_report_bug;
    QAction *action_contact_us;
    QAction *action_about_kalimat;
    QAction *action_help_keyboard;
    QAction *mnuProgramRun;
    QAction *actionCompile;
    QAction *action_save;
    QAction *action_open;
    QAction *action_verify;
    QAction *action_new;
    QAction *action_saveas;
    QAction *action_exit;
    QAction *action_edit_cut;
    QAction *action_edit_copy;
    QAction *action_edit_paste;
    QAction *action_delete;
    QAction *action_undo;
    QAction *action_redo;
    QAction *garbageCollect;
    QAction *actionDummy;
    QAction *action_wonderfulmonitor;
    QAction *action_shift;
    QAction *action_2;
    QAction *action_shift_2;
    QAction *action_shift_3;
    QAction *action_shift_4;
    QAction *action_shift_5;
    QAction *action_shift_6;
    QAction *action_find;
    QAction *action_replace;
    QAction *actionSpeedFast;
    QAction *actionSpeedMedium;
    QAction *actionSpeedSlow;
    QAction *actionCompile_without_tags;
    QAction *actionGo_to_position;
    QAction *actionSpeedSuper;
    QAction *actionSpecialSymbol_dot;
    QAction *action_SpecialSymbol_comma;
    QAction *action_SpecialSymbol_closeBracket;
    QAction *action_SpecialSymbol_openBracket;
    QAction *action_SpecialSymbol_closeBrace;
    QAction *action_SpecialSymbol_openBrace;
    QAction *action_copy_as_html;
    QAction *action_copy_as_wiki;
    QAction *action_copy_literate_html;
    QAction *action_autoFormat;
    QAction *action_options;
    QAction *action_breakpoint;
    QAction *action_resume;
    QAction *action_step;
    QAction *action_step_procedure;
    QAction *action_step_parameters;
    QAction *actionMake_exe;
    QAction *actionParse_with_recovery;
    QAction *actionUpdate_code_model;
    QAction *action_go_to_definition;
    QAction *action_SpecialSymbol_lambda;
    QAction *actionLambda_transformation;
    QWidget *centralWidget;
    QVBoxLayout *verticalLayout_3;
    QTabWidget *editorTabs;
    QTabWidget *tabWidget;
    QWidget *tab;
    QVBoxLayout *verticalLayout_2;
    QTextBrowser *outputView;
    QWidget *tab_2;
    QVBoxLayout *verticalLayout;
    QGraphicsView *graphicsView;
    QMenuBar *menuBar;
    QMenu *mnuFile;
    QMenu *mnuRecentFiles_2;
    QMenu *mnuEdit;
    QMenu *mnuPRogram;
    QMenu *mnuHelp;
    QMenu *mnuTest;
    QMenu *mnuSpecialSymbol;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;
    QDockWidget *dockSearchReplace;
    QWidget *dockWidgetContents;
    QLabel *label;
    QLabel *label_2;
    QLineEdit *txtSearchString;
    QLineEdit *txtReplacementString;
    QPushButton *btnFindPrev;
    QPushButton *btnFindNext;
    QPushButton *btnReplacePrev;
    QPushButton *btnReplaceNext;
    QLabel *lblFindStatus;
    QToolBar *functionNavigationToolbar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(782, 895);
        QIcon icon;
        icon.addFile(QStringLiteral(":/icons/icons/kalimat.ico"), QSize(), QIcon::Normal, QIcon::Off);
        MainWindow->setWindowIcon(icon);
        MainWindow->setLayoutDirection(Qt::RightToLeft);
        MainWindow->setAutoFillBackground(false);
        MainWindow->setDockNestingEnabled(false);
        actionLexize = new QAction(MainWindow);
        actionLexize->setObjectName(QStringLiteral("actionLexize"));
        actionParse = new QAction(MainWindow);
        actionParse->setObjectName(QStringLiteral("actionParse"));
        actionEvaluate = new QAction(MainWindow);
        actionEvaluate->setObjectName(QStringLiteral("actionEvaluate"));
        actionKalimatManual = new QAction(MainWindow);
        actionKalimatManual->setObjectName(QStringLiteral("actionKalimatManual"));
        actionKalimatManual->setVisible(false);
        action_walkthroughs = new QAction(MainWindow);
        action_walkthroughs->setObjectName(QStringLiteral("action_walkthroughs"));
        action_walkthroughs->setVisible(false);
        action_report_bug = new QAction(MainWindow);
        action_report_bug->setObjectName(QStringLiteral("action_report_bug"));
        action_report_bug->setVisible(false);
        action_contact_us = new QAction(MainWindow);
        action_contact_us->setObjectName(QStringLiteral("action_contact_us"));
        action_about_kalimat = new QAction(MainWindow);
        action_about_kalimat->setObjectName(QStringLiteral("action_about_kalimat"));
        action_help_keyboard = new QAction(MainWindow);
        action_help_keyboard->setObjectName(QStringLiteral("action_help_keyboard"));
        action_help_keyboard->setVisible(false);
        mnuProgramRun = new QAction(MainWindow);
        mnuProgramRun->setObjectName(QStringLiteral("mnuProgramRun"));
        QIcon icon1;
        icon1.addFile(QStringLiteral(":/icons/icons/runIcon.png"), QSize(), QIcon::Normal, QIcon::Off);
        mnuProgramRun->setIcon(icon1);
        actionCompile = new QAction(MainWindow);
        actionCompile->setObjectName(QStringLiteral("actionCompile"));
        action_save = new QAction(MainWindow);
        action_save->setObjectName(QStringLiteral("action_save"));
        QIcon icon2;
        icon2.addFile(QStringLiteral(":/icons/icons/saveIcon.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_save->setIcon(icon2);
        action_open = new QAction(MainWindow);
        action_open->setObjectName(QStringLiteral("action_open"));
        QIcon icon3;
        icon3.addFile(QStringLiteral(":/icons/icons/openIcon.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_open->setIcon(icon3);
        action_verify = new QAction(MainWindow);
        action_verify->setObjectName(QStringLiteral("action_verify"));
        QIcon icon4;
        icon4.addFile(QStringLiteral(":/icons/icons/checkIcon.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_verify->setIcon(icon4);
        action_new = new QAction(MainWindow);
        action_new->setObjectName(QStringLiteral("action_new"));
        QIcon icon5;
        icon5.addFile(QStringLiteral(":/icons/icons/newIcon.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_new->setIcon(icon5);
        action_saveas = new QAction(MainWindow);
        action_saveas->setObjectName(QStringLiteral("action_saveas"));
        action_exit = new QAction(MainWindow);
        action_exit->setObjectName(QStringLiteral("action_exit"));
        action_edit_cut = new QAction(MainWindow);
        action_edit_cut->setObjectName(QStringLiteral("action_edit_cut"));
        action_edit_copy = new QAction(MainWindow);
        action_edit_copy->setObjectName(QStringLiteral("action_edit_copy"));
        action_edit_paste = new QAction(MainWindow);
        action_edit_paste->setObjectName(QStringLiteral("action_edit_paste"));
        action_delete = new QAction(MainWindow);
        action_delete->setObjectName(QStringLiteral("action_delete"));
        action_undo = new QAction(MainWindow);
        action_undo->setObjectName(QStringLiteral("action_undo"));
        action_redo = new QAction(MainWindow);
        action_redo->setObjectName(QStringLiteral("action_redo"));
        garbageCollect = new QAction(MainWindow);
        garbageCollect->setObjectName(QStringLiteral("garbageCollect"));
        actionDummy = new QAction(MainWindow);
        actionDummy->setObjectName(QStringLiteral("actionDummy"));
        action_wonderfulmonitor = new QAction(MainWindow);
        action_wonderfulmonitor->setObjectName(QStringLiteral("action_wonderfulmonitor"));
        action_wonderfulmonitor->setCheckable(true);
        action_shift = new QAction(MainWindow);
        action_shift->setObjectName(QStringLiteral("action_shift"));
        action_2 = new QAction(MainWindow);
        action_2->setObjectName(QStringLiteral("action_2"));
        action_shift_2 = new QAction(MainWindow);
        action_shift_2->setObjectName(QStringLiteral("action_shift_2"));
        action_shift_3 = new QAction(MainWindow);
        action_shift_3->setObjectName(QStringLiteral("action_shift_3"));
        action_shift_4 = new QAction(MainWindow);
        action_shift_4->setObjectName(QStringLiteral("action_shift_4"));
        action_shift_5 = new QAction(MainWindow);
        action_shift_5->setObjectName(QStringLiteral("action_shift_5"));
        action_shift_6 = new QAction(MainWindow);
        action_shift_6->setObjectName(QStringLiteral("action_shift_6"));
        action_find = new QAction(MainWindow);
        action_find->setObjectName(QStringLiteral("action_find"));
        action_replace = new QAction(MainWindow);
        action_replace->setObjectName(QStringLiteral("action_replace"));
        actionSpeedFast = new QAction(MainWindow);
        actionSpeedFast->setObjectName(QStringLiteral("actionSpeedFast"));
        actionSpeedFast->setCheckable(true);
        actionSpeedMedium = new QAction(MainWindow);
        actionSpeedMedium->setObjectName(QStringLiteral("actionSpeedMedium"));
        actionSpeedMedium->setCheckable(true);
        actionSpeedMedium->setChecked(true);
        actionSpeedSlow = new QAction(MainWindow);
        actionSpeedSlow->setObjectName(QStringLiteral("actionSpeedSlow"));
        actionSpeedSlow->setCheckable(true);
        actionSpeedSlow->setChecked(false);
        actionCompile_without_tags = new QAction(MainWindow);
        actionCompile_without_tags->setObjectName(QStringLiteral("actionCompile_without_tags"));
        actionGo_to_position = new QAction(MainWindow);
        actionGo_to_position->setObjectName(QStringLiteral("actionGo_to_position"));
        actionSpeedSuper = new QAction(MainWindow);
        actionSpeedSuper->setObjectName(QStringLiteral("actionSpeedSuper"));
        actionSpeedSuper->setCheckable(true);
        actionSpecialSymbol_dot = new QAction(MainWindow);
        actionSpecialSymbol_dot->setObjectName(QStringLiteral("actionSpecialSymbol_dot"));
        action_SpecialSymbol_comma = new QAction(MainWindow);
        action_SpecialSymbol_comma->setObjectName(QStringLiteral("action_SpecialSymbol_comma"));
        action_SpecialSymbol_closeBracket = new QAction(MainWindow);
        action_SpecialSymbol_closeBracket->setObjectName(QStringLiteral("action_SpecialSymbol_closeBracket"));
        action_SpecialSymbol_openBracket = new QAction(MainWindow);
        action_SpecialSymbol_openBracket->setObjectName(QStringLiteral("action_SpecialSymbol_openBracket"));
        action_SpecialSymbol_closeBrace = new QAction(MainWindow);
        action_SpecialSymbol_closeBrace->setObjectName(QStringLiteral("action_SpecialSymbol_closeBrace"));
        action_SpecialSymbol_openBrace = new QAction(MainWindow);
        action_SpecialSymbol_openBrace->setObjectName(QStringLiteral("action_SpecialSymbol_openBrace"));
        action_copy_as_html = new QAction(MainWindow);
        action_copy_as_html->setObjectName(QStringLiteral("action_copy_as_html"));
        action_copy_as_wiki = new QAction(MainWindow);
        action_copy_as_wiki->setObjectName(QStringLiteral("action_copy_as_wiki"));
        action_copy_literate_html = new QAction(MainWindow);
        action_copy_literate_html->setObjectName(QStringLiteral("action_copy_literate_html"));
        action_copy_literate_html->setVisible(false);
        action_autoFormat = new QAction(MainWindow);
        action_autoFormat->setObjectName(QStringLiteral("action_autoFormat"));
        QIcon icon6;
        icon6.addFile(QStringLiteral(":/icons/icons/formatIcon.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_autoFormat->setIcon(icon6);
        action_options = new QAction(MainWindow);
        action_options->setObjectName(QStringLiteral("action_options"));
        action_breakpoint = new QAction(MainWindow);
        action_breakpoint->setObjectName(QStringLiteral("action_breakpoint"));
        QIcon icon7;
        icon7.addFile(QStringLiteral(":/icons/icons/stopIcon.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_breakpoint->setIcon(icon7);
        action_breakpoint->setVisible(true);
        action_resume = new QAction(MainWindow);
        action_resume->setObjectName(QStringLiteral("action_resume"));
        QIcon icon8;
        icon8.addFile(QStringLiteral(":/icons/icons/resumeIcon.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_resume->setIcon(icon8);
        action_resume->setVisible(true);
        action_step = new QAction(MainWindow);
        action_step->setObjectName(QStringLiteral("action_step"));
        QIcon icon9;
        icon9.addFile(QStringLiteral(":/icons/icons/stepIcon.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_step->setIcon(icon9);
        action_step->setVisible(true);
        action_step_procedure = new QAction(MainWindow);
        action_step_procedure->setObjectName(QStringLiteral("action_step_procedure"));
        QIcon icon10;
        icon10.addFile(QStringLiteral(":/icons/icons/stepCallIcon.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_step_procedure->setIcon(icon10);
        action_step_procedure->setVisible(true);
        action_step_parameters = new QAction(MainWindow);
        action_step_parameters->setObjectName(QStringLiteral("action_step_parameters"));
        QIcon icon11;
        icon11.addFile(QStringLiteral(":/icons/icons/stepParamsIcon.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_step_parameters->setIcon(icon11);
        action_step_parameters->setVisible(true);
        actionMake_exe = new QAction(MainWindow);
        actionMake_exe->setObjectName(QStringLiteral("actionMake_exe"));
        actionParse_with_recovery = new QAction(MainWindow);
        actionParse_with_recovery->setObjectName(QStringLiteral("actionParse_with_recovery"));
        actionUpdate_code_model = new QAction(MainWindow);
        actionUpdate_code_model->setObjectName(QStringLiteral("actionUpdate_code_model"));
        action_go_to_definition = new QAction(MainWindow);
        action_go_to_definition->setObjectName(QStringLiteral("action_go_to_definition"));
        action_SpecialSymbol_lambda = new QAction(MainWindow);
        action_SpecialSymbol_lambda->setObjectName(QStringLiteral("action_SpecialSymbol_lambda"));
        actionLambda_transformation = new QAction(MainWindow);
        actionLambda_transformation->setObjectName(QStringLiteral("actionLambda_transformation"));
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        QSizePolicy sizePolicy(QSizePolicy::MinimumExpanding, QSizePolicy::MinimumExpanding);
        sizePolicy.setHorizontalStretch(100);
        sizePolicy.setVerticalStretch(100);
        sizePolicy.setHeightForWidth(centralWidget->sizePolicy().hasHeightForWidth());
        centralWidget->setSizePolicy(sizePolicy);
        centralWidget->setLayoutDirection(Qt::LeftToRight);
        centralWidget->setAutoFillBackground(false);
        verticalLayout_3 = new QVBoxLayout(centralWidget);
        verticalLayout_3->setSpacing(6);
        verticalLayout_3->setContentsMargins(11, 11, 11, 11);
        verticalLayout_3->setObjectName(QStringLiteral("verticalLayout_3"));
        editorTabs = new QTabWidget(centralWidget);
        editorTabs->setObjectName(QStringLiteral("editorTabs"));
        QSizePolicy sizePolicy1(QSizePolicy::Ignored, QSizePolicy::MinimumExpanding);
        sizePolicy1.setHorizontalStretch(0);
        sizePolicy1.setVerticalStretch(8);
        sizePolicy1.setHeightForWidth(editorTabs->sizePolicy().hasHeightForWidth());
        editorTabs->setSizePolicy(sizePolicy1);
        editorTabs->setMinimumSize(QSize(0, 400));
        editorTabs->setTabsClosable(true);

        verticalLayout_3->addWidget(editorTabs);

        tabWidget = new QTabWidget(centralWidget);
        tabWidget->setObjectName(QStringLiteral("tabWidget"));
        QSizePolicy sizePolicy2(QSizePolicy::Expanding, QSizePolicy::Preferred);
        sizePolicy2.setHorizontalStretch(0);
        sizePolicy2.setVerticalStretch(2);
        sizePolicy2.setHeightForWidth(tabWidget->sizePolicy().hasHeightForWidth());
        tabWidget->setSizePolicy(sizePolicy2);
        tabWidget->setTabShape(QTabWidget::Triangular);
        tabWidget->setDocumentMode(true);
        tab = new QWidget();
        tab->setObjectName(QStringLiteral("tab"));
        verticalLayout_2 = new QVBoxLayout(tab);
        verticalLayout_2->setSpacing(6);
        verticalLayout_2->setContentsMargins(11, 11, 11, 11);
        verticalLayout_2->setObjectName(QStringLiteral("verticalLayout_2"));
        outputView = new QTextBrowser(tab);
        outputView->setObjectName(QStringLiteral("outputView"));
        QSizePolicy sizePolicy3(QSizePolicy::Ignored, QSizePolicy::Preferred);
        sizePolicy3.setHorizontalStretch(0);
        sizePolicy3.setVerticalStretch(2);
        sizePolicy3.setHeightForWidth(outputView->sizePolicy().hasHeightForWidth());
        outputView->setSizePolicy(sizePolicy3);
        outputView->setMinimumSize(QSize(451, 0));
        outputView->setLayoutDirection(Qt::RightToLeft);

        verticalLayout_2->addWidget(outputView);

        tabWidget->addTab(tab, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName(QStringLiteral("tab_2"));
        verticalLayout = new QVBoxLayout(tab_2);
        verticalLayout->setSpacing(6);
        verticalLayout->setContentsMargins(11, 11, 11, 11);
        verticalLayout->setObjectName(QStringLiteral("verticalLayout"));
        graphicsView = new QGraphicsView(tab_2);
        graphicsView->setObjectName(QStringLiteral("graphicsView"));
        QSizePolicy sizePolicy4(QSizePolicy::Expanding, QSizePolicy::Preferred);
        sizePolicy4.setHorizontalStretch(0);
        sizePolicy4.setVerticalStretch(0);
        sizePolicy4.setHeightForWidth(graphicsView->sizePolicy().hasHeightForWidth());
        graphicsView->setSizePolicy(sizePolicy4);
        QFont font;
        font.setFamily(QStringLiteral("Courier New"));
        font.setPointSize(14);
        graphicsView->setFont(font);

        verticalLayout->addWidget(graphicsView);

        tabWidget->addTab(tab_2, QString());

        verticalLayout_3->addWidget(tabWidget);

        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 782, 18));
        menuBar->setLayoutDirection(Qt::RightToLeft);
        menuBar->setLocale(QLocale(QLocale::Arabic, QLocale::Egypt));
        mnuFile = new QMenu(menuBar);
        mnuFile->setObjectName(QStringLiteral("mnuFile"));
        mnuRecentFiles_2 = new QMenu(mnuFile);
        mnuRecentFiles_2->setObjectName(QStringLiteral("mnuRecentFiles_2"));
        mnuRecentFiles_2->setLayoutDirection(Qt::RightToLeft);
        mnuEdit = new QMenu(menuBar);
        mnuEdit->setObjectName(QStringLiteral("mnuEdit"));
        mnuPRogram = new QMenu(menuBar);
        mnuPRogram->setObjectName(QStringLiteral("mnuPRogram"));
        mnuHelp = new QMenu(menuBar);
        mnuHelp->setObjectName(QStringLiteral("mnuHelp"));
        mnuHelp->setTearOffEnabled(false);
        mnuHelp->setSeparatorsCollapsible(false);
        mnuTest = new QMenu(menuBar);
        mnuTest->setObjectName(QStringLiteral("mnuTest"));
        mnuSpecialSymbol = new QMenu(menuBar);
        mnuSpecialSymbol->setObjectName(QStringLiteral("mnuSpecialSymbol"));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        mainToolBar->setIconSize(QSize(31, 31));
        mainToolBar->setToolButtonStyle(Qt::ToolButtonTextUnderIcon);
        mainToolBar->setFloatable(false);
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        MainWindow->setStatusBar(statusBar);
        dockSearchReplace = new QDockWidget(MainWindow);
        dockSearchReplace->setObjectName(QStringLiteral("dockSearchReplace"));
        QSizePolicy sizePolicy5(QSizePolicy::Preferred, QSizePolicy::Maximum);
        sizePolicy5.setHorizontalStretch(0);
        sizePolicy5.setVerticalStretch(0);
        sizePolicy5.setHeightForWidth(dockSearchReplace->sizePolicy().hasHeightForWidth());
        dockSearchReplace->setSizePolicy(sizePolicy5);
        dockSearchReplace->setMinimumSize(QSize(79, 100));
        dockSearchReplace->setLayoutDirection(Qt::RightToLeft);
        dockSearchReplace->setFeatures(QDockWidget::AllDockWidgetFeatures);
        dockWidgetContents = new QWidget();
        dockWidgetContents->setObjectName(QStringLiteral("dockWidgetContents"));
        label = new QLabel(dockWidgetContents);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(630, 10, 131, 20));
        label->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_2 = new QLabel(dockWidgetContents);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(630, 40, 131, 20));
        label_2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        txtSearchString = new QLineEdit(dockWidgetContents);
        txtSearchString->setObjectName(QStringLiteral("txtSearchString"));
        txtSearchString->setGeometry(QRect(262, 10, 351, 20));
        txtSearchString->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        txtReplacementString = new QLineEdit(dockWidgetContents);
        txtReplacementString->setObjectName(QStringLiteral("txtReplacementString"));
        txtReplacementString->setGeometry(QRect(262, 40, 351, 20));
        txtReplacementString->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        btnFindPrev = new QPushButton(dockWidgetContents);
        btnFindPrev->setObjectName(QStringLiteral("btnFindPrev"));
        btnFindPrev->setGeometry(QRect(230, 10, 21, 23));
        btnFindNext = new QPushButton(dockWidgetContents);
        btnFindNext->setObjectName(QStringLiteral("btnFindNext"));
        btnFindNext->setGeometry(QRect(210, 10, 21, 23));
        btnFindNext->setAutoDefault(true);
        btnReplacePrev = new QPushButton(dockWidgetContents);
        btnReplacePrev->setObjectName(QStringLiteral("btnReplacePrev"));
        btnReplacePrev->setGeometry(QRect(230, 40, 21, 23));
        btnReplaceNext = new QPushButton(dockWidgetContents);
        btnReplaceNext->setObjectName(QStringLiteral("btnReplaceNext"));
        btnReplaceNext->setGeometry(QRect(210, 40, 21, 23));
        lblFindStatus = new QLabel(dockWidgetContents);
        lblFindStatus->setObjectName(QStringLiteral("lblFindStatus"));
        lblFindStatus->setGeometry(QRect(10, 10, 181, 16));
        dockSearchReplace->setWidget(dockWidgetContents);
        MainWindow->addDockWidget(static_cast<Qt::DockWidgetArea>(4), dockSearchReplace);
        functionNavigationToolbar = new QToolBar(MainWindow);
        functionNavigationToolbar->setObjectName(QStringLiteral("functionNavigationToolbar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, functionNavigationToolbar);
        MainWindow->insertToolBarBreak(functionNavigationToolbar);

        menuBar->addAction(mnuFile->menuAction());
        menuBar->addAction(mnuEdit->menuAction());
        menuBar->addAction(mnuPRogram->menuAction());
        menuBar->addAction(mnuTest->menuAction());
        menuBar->addAction(mnuSpecialSymbol->menuAction());
        menuBar->addAction(mnuHelp->menuAction());
        mnuFile->addAction(action_new);
        mnuFile->addAction(action_open);
        mnuFile->addAction(mnuRecentFiles_2->menuAction());
        mnuFile->addAction(action_save);
        mnuFile->addAction(action_saveas);
        mnuFile->addSeparator();
        mnuFile->addAction(action_exit);
        mnuRecentFiles_2->addAction(actionDummy);
        mnuEdit->addAction(action_undo);
        mnuEdit->addAction(action_redo);
        mnuEdit->addSeparator();
        mnuEdit->addAction(action_edit_cut);
        mnuEdit->addAction(action_edit_copy);
        mnuEdit->addAction(action_edit_paste);
        mnuEdit->addAction(action_delete);
        mnuEdit->addSeparator();
        mnuEdit->addAction(action_find);
        mnuEdit->addAction(action_replace);
        mnuEdit->addAction(action_copy_as_html);
        mnuEdit->addAction(action_copy_as_wiki);
        mnuEdit->addAction(action_copy_literate_html);
        mnuEdit->addSeparator();
        mnuEdit->addAction(action_autoFormat);
        mnuEdit->addSeparator();
        mnuEdit->addAction(action_options);
        mnuPRogram->addAction(mnuProgramRun);
        mnuPRogram->addAction(action_verify);
        mnuPRogram->addAction(garbageCollect);
        mnuPRogram->addAction(action_wonderfulmonitor);
        mnuPRogram->addAction(actionSpeedFast);
        mnuPRogram->addAction(actionSpeedMedium);
        mnuPRogram->addAction(actionSpeedSlow);
        mnuPRogram->addAction(actionSpeedSuper);
        mnuPRogram->addSeparator();
        mnuPRogram->addAction(action_breakpoint);
        mnuPRogram->addAction(action_resume);
        mnuPRogram->addAction(action_step);
        mnuPRogram->addAction(action_step_procedure);
        mnuPRogram->addAction(action_step_parameters);
        mnuPRogram->addSeparator();
        mnuPRogram->addAction(actionMake_exe);
        mnuPRogram->addSeparator();
        mnuPRogram->addAction(action_go_to_definition);
        mnuHelp->addAction(actionKalimatManual);
        mnuHelp->addAction(action_help_keyboard);
        mnuHelp->addAction(action_walkthroughs);
        mnuHelp->addAction(action_report_bug);
        mnuHelp->addAction(action_about_kalimat);
        mnuTest->addAction(actionLexize);
        mnuTest->addAction(actionParse);
        mnuTest->addAction(actionCompile);
        mnuTest->addAction(actionCompile_without_tags);
        mnuTest->addAction(actionEvaluate);
        mnuTest->addAction(actionGo_to_position);
        mnuTest->addAction(actionParse_with_recovery);
        mnuTest->addAction(actionUpdate_code_model);
        mnuTest->addAction(actionLambda_transformation);
        mnuSpecialSymbol->addAction(actionSpecialSymbol_dot);
        mnuSpecialSymbol->addAction(action_SpecialSymbol_comma);
        mnuSpecialSymbol->addAction(action_SpecialSymbol_openBracket);
        mnuSpecialSymbol->addAction(action_SpecialSymbol_closeBracket);
        mnuSpecialSymbol->addAction(action_SpecialSymbol_openBrace);
        mnuSpecialSymbol->addAction(action_SpecialSymbol_closeBrace);
        mnuSpecialSymbol->addAction(action_SpecialSymbol_lambda);
        mainToolBar->addAction(action_new);
        mainToolBar->addAction(action_open);
        mainToolBar->addAction(action_save);
        mainToolBar->addSeparator();
        mainToolBar->addAction(action_autoFormat);
        mainToolBar->addAction(mnuProgramRun);
        mainToolBar->addSeparator();
        mainToolBar->addAction(action_breakpoint);
        mainToolBar->addAction(action_resume);
        mainToolBar->addAction(action_step);
        mainToolBar->addAction(action_step_procedure);

        retranslateUi(MainWindow);

        tabWidget->setCurrentIndex(1);
        btnFindNext->setDefault(true);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", 0));
        actionLexize->setText(QApplication::translate("MainWindow", "Lexize", 0));
        actionParse->setText(QApplication::translate("MainWindow", "Parse", 0));
        actionParse->setShortcut(QApplication::translate("MainWindow", "Ctrl+P", 0));
        actionEvaluate->setText(QApplication::translate("MainWindow", "Evaluate", 0));
        actionKalimatManual->setText(QApplication::translate("MainWindow", "\330\247\331\204\330\250\330\261\331\205\330\254\330\251 \330\250\331\203\331\204\331\205\330\247\330\252", 0));
        actionKalimatManual->setShortcut(QApplication::translate("MainWindow", "F1", 0));
        action_walkthroughs->setText(QApplication::translate("MainWindow", "\331\205\330\255\330\247\330\266\330\261\330\247\330\252 \330\271\331\205\331\204\331\212\330\251", 0));
        action_report_bug->setText(QApplication::translate("MainWindow", "\330\245\330\250\331\204\330\247\330\272 \330\271\331\206 \330\256\330\267\330\243 \330\250\330\247\331\204\330\250\330\261\331\206\330\247\331\205\330\254", 0));
        action_contact_us->setText(QApplication::translate("MainWindow", "\330\247\330\252\330\265\331\204 \330\250\331\206\330\247", 0));
        action_about_kalimat->setText(QApplication::translate("MainWindow", "\330\271\331\206 \331\203\331\204\331\205\330\247\330\252...", 0));
        action_help_keyboard->setText(QApplication::translate("MainWindow", "\330\247\331\204\330\271\331\204\330\247\331\205\330\247\330\252 \330\247\331\204\330\256\330\247\330\265\330\251 \331\210\331\204\331\210\330\255\330\251 \330\247\331\204\331\205\331\201\330\247\330\252\331\212\330\255", 0));
        mnuProgramRun->setText(QApplication::translate("MainWindow", "\330\252\331\206\331\201\331\212\330\260", 0));
        mnuProgramRun->setShortcut(QApplication::translate("MainWindow", "Ctrl+R", 0));
        actionCompile->setText(QApplication::translate("MainWindow", "Compile", 0));
        actionCompile->setShortcut(QApplication::translate("MainWindow", "Ctrl+M", 0));
        action_save->setText(QApplication::translate("MainWindow", "\330\255\331\201\330\270", 0));
        action_save->setShortcut(QApplication::translate("MainWindow", "Ctrl+S", 0));
        action_open->setText(QApplication::translate("MainWindow", "\331\201\330\252\330\255", 0));
        action_open->setShortcut(QApplication::translate("MainWindow", "Ctrl+O", 0));
        action_verify->setText(QApplication::translate("MainWindow", "\330\252\330\255\331\202\331\221\331\202", 0));
        action_new->setText(QApplication::translate("MainWindow", "\330\254\330\257\331\212\330\257", 0));
        action_new->setShortcut(QApplication::translate("MainWindow", "Ctrl+N", 0));
        action_saveas->setText(QApplication::translate("MainWindow", "\330\255\331\201\330\270 \330\250\330\245\330\263\331\205...", 0));
        action_exit->setText(QApplication::translate("MainWindow", "\330\256\330\261\331\210\330\254", 0));
        action_edit_cut->setText(QApplication::translate("MainWindow", "\331\202\330\265", 0));
        action_edit_cut->setShortcut(QApplication::translate("MainWindow", "Ctrl+X", 0));
        action_edit_copy->setText(QApplication::translate("MainWindow", "\331\206\330\263\330\256", 0));
        action_edit_copy->setShortcut(QApplication::translate("MainWindow", "Ctrl+C", 0));
        action_edit_paste->setText(QApplication::translate("MainWindow", "\331\204\330\265\331\202", 0));
        action_edit_paste->setShortcut(QApplication::translate("MainWindow", "Ctrl+V", 0));
        action_delete->setText(QApplication::translate("MainWindow", "\331\205\330\263\330\255", 0));
        action_undo->setText(QApplication::translate("MainWindow", "\330\252\330\261\330\247\330\254\330\271", 0));
        action_undo->setShortcut(QApplication::translate("MainWindow", "Ctrl+Z", 0));
        action_redo->setText(QApplication::translate("MainWindow", "\330\245\330\271\330\247\330\257\330\251", 0));
        garbageCollect->setText(QApplication::translate("MainWindow", "\330\254\331\205\330\271 \330\247\331\204\331\205\331\207\331\205\331\204\330\247\330\252", 0));
        actionDummy->setText(QApplication::translate("MainWindow", "dummy", 0));
        action_wonderfulmonitor->setText(QApplication::translate("MainWindow", "\330\247\331\204\331\205\330\261\330\247\331\202\330\250 \330\247\331\204\330\271\330\254\331\212\330\250", 0));
        action_shift->setText(QApplication::translate("MainWindow", "<     (shift+\330\254)", 0));
        action_2->setText(QApplication::translate("MainWindow", ">     (shift+\330\257)", 0));
        action_shift_2->setText(QApplication::translate("MainWindow", "\330\214     (shift+\331\206)", 0));
        action_shift_3->setText(QApplication::translate("MainWindow", "[     (shift+\330\250)", 0));
        action_shift_4->setText(QApplication::translate("MainWindow", "]     (shift+\331\212)", 0));
        action_shift_5->setText(QApplication::translate("MainWindow", ".     (shift+\330\262)", 0));
        action_shift_6->setText(QApplication::translate("MainWindow", "\330\245     (shift+\330\272)", 0));
        action_find->setText(QApplication::translate("MainWindow", "\330\250\330\255\330\253...", 0));
        action_find->setShortcut(QApplication::translate("MainWindow", "Ctrl+F", 0));
        action_replace->setText(QApplication::translate("MainWindow", "\330\247\330\263\330\252\330\250\330\257\330\247\331\204...", 0));
        actionSpeedFast->setText(QApplication::translate("MainWindow", "\330\263\330\261\331\212\330\271", 0));
        actionSpeedFast->setShortcut(QApplication::translate("MainWindow", "Alt+Q", 0));
        actionSpeedMedium->setText(QApplication::translate("MainWindow", "\331\205\330\252\331\210\330\263\330\267", 0));
        actionSpeedMedium->setShortcut(QApplication::translate("MainWindow", "Alt+A", 0));
        actionSpeedSlow->setText(QApplication::translate("MainWindow", "\330\250\330\267\331\212\330\241", 0));
        actionSpeedSlow->setShortcut(QApplication::translate("MainWindow", "Alt+Z", 0));
        actionCompile_without_tags->setText(QApplication::translate("MainWindow", "Compile without tags", 0));
        actionGo_to_position->setText(QApplication::translate("MainWindow", "Go to position", 0));
        actionGo_to_position->setShortcut(QApplication::translate("MainWindow", "Ctrl+G", 0));
        actionSpeedSuper->setText(QApplication::translate("MainWindow", "\330\256\330\247\330\261\331\202", 0));
        actionSpecialSymbol_dot->setText(QApplication::translate("MainWindow", ".", 0));
        actionSpecialSymbol_dot->setShortcut(QApplication::translate("MainWindow", "Ctrl+.", 0));
        action_SpecialSymbol_comma->setText(QApplication::translate("MainWindow", ",", 0));
        action_SpecialSymbol_comma->setShortcut(QApplication::translate("MainWindow", "Ctrl+,", 0));
        action_SpecialSymbol_closeBracket->setText(QApplication::translate("MainWindow", "[", 0));
        action_SpecialSymbol_closeBracket->setShortcut(QApplication::translate("MainWindow", "Ctrl+[", 0));
        action_SpecialSymbol_openBracket->setText(QApplication::translate("MainWindow", "]", 0));
        action_SpecialSymbol_openBracket->setShortcut(QApplication::translate("MainWindow", "Ctrl+]", 0));
        action_SpecialSymbol_closeBrace->setText(QApplication::translate("MainWindow", "{", 0));
        action_SpecialSymbol_closeBrace->setShortcut(QApplication::translate("MainWindow", "Ctrl+Alt+[", 0));
        action_SpecialSymbol_openBrace->setText(QApplication::translate("MainWindow", "}", 0));
        action_SpecialSymbol_openBrace->setShortcut(QApplication::translate("MainWindow", "Ctrl+Alt+]", 0));
        action_copy_as_html->setText(QApplication::translate("MainWindow", "\331\206\330\263\330\256 \330\250\330\265\331\212\330\272\330\251 HTML", 0));
        action_copy_as_wiki->setText(QApplication::translate("MainWindow", "\331\206\330\263\330\256 \330\250\330\265\331\212\330\272\330\251 wiki", 0));
        action_copy_literate_html->setText(QApplication::translate("MainWindow", "\331\206\330\263\330\256 \330\250\330\247\331\204\330\264\330\261\330\255\330\233HTML", 0));
        action_autoFormat->setText(QApplication::translate("MainWindow", "\330\252\331\206\330\263\331\212\331\202", 0));
        action_autoFormat->setShortcut(QApplication::translate("MainWindow", "Ctrl+I", 0));
        action_options->setText(QApplication::translate("MainWindow", "\330\256\331\212\330\247\330\261\330\247\330\252...", 0));
        action_breakpoint->setText(QApplication::translate("MainWindow", "\330\252\331\210\331\202\331\201 \331\207\331\206\330\247", 0));
        action_breakpoint->setShortcut(QApplication::translate("MainWindow", "F9", 0));
        action_resume->setText(QApplication::translate("MainWindow", "\330\247\331\203\331\205\331\204", 0));
        action_resume->setShortcut(QApplication::translate("MainWindow", "F5", 0));
        action_step->setText(QApplication::translate("MainWindow", "\330\256\330\267\331\210\330\251", 0));
        action_step->setShortcut(QApplication::translate("MainWindow", "F11", 0));
        action_step_procedure->setText(QApplication::translate("MainWindow", "\331\202\331\201\330\262 \330\247\330\263\330\252\330\257\330\271\330\247\330\241", 0));
        action_step_procedure->setShortcut(QApplication::translate("MainWindow", "F10", 0));
        action_step_parameters->setText(QApplication::translate("MainWindow", "\331\202\331\201\330\262 \330\271\331\210\330\247\331\205\331\204", 0));
        action_step_parameters->setShortcut(QApplication::translate("MainWindow", "Shift+F10", 0));
        actionMake_exe->setText(QApplication::translate("MainWindow", "\330\271\331\205\331\204 \331\205\331\204\331\201 \330\252\331\206\331\201\331\212\330\260\331\212...", 0));
        actionParse_with_recovery->setText(QApplication::translate("MainWindow", "Parse with recovery", 0));
        actionUpdate_code_model->setText(QApplication::translate("MainWindow", "Update code model", 0));
        action_go_to_definition->setText(QApplication::translate("MainWindow", "\330\260\331\207\330\247\330\250 \331\204\330\252\330\271\330\261\331\212\331\201", 0));
        action_go_to_definition->setShortcut(QApplication::translate("MainWindow", "F2", 0));
        action_SpecialSymbol_lambda->setText(QApplication::translate("MainWindow", "\316\273", 0));
        action_SpecialSymbol_lambda->setShortcut(QApplication::translate("MainWindow", "Ctrl+L", 0));
        actionLambda_transformation->setText(QApplication::translate("MainWindow", "Lambda transformation", 0));
        tabWidget->setTabText(tabWidget->indexOf(tab), QApplication::translate("MainWindow", "\330\247\331\204\330\261\330\263\330\247\330\246\331\204", 0));
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QApplication::translate("MainWindow", "\330\247\331\204\331\205\330\252\330\272\331\212\330\261\330\247\330\252", 0));
        mnuFile->setTitle(QApplication::translate("MainWindow", "\331\205\331\204\331\201", 0));
        mnuRecentFiles_2->setTitle(QApplication::translate("MainWindow", "\331\205\331\204\331\201\330\247\330\252 \330\263\330\247\330\250\331\202\330\251", 0));
        mnuEdit->setTitle(QApplication::translate("MainWindow", "\330\252\330\255\330\261\331\212\330\261", 0));
        mnuPRogram->setTitle(QApplication::translate("MainWindow", "\330\250\330\261\331\206\330\247\331\205\330\254", 0));
        mnuHelp->setTitle(QApplication::translate("MainWindow", "\331\205\330\263\330\247\330\271\330\257\330\251", 0));
        mnuTest->setTitle(QApplication::translate("MainWindow", "\330\247\330\256\330\252\330\250\330\247\330\261", 0));
        mnuSpecialSymbol->setTitle(QApplication::translate("MainWindow", "\330\261\331\205\330\262 \330\256\330\247\330\265", 0));
        label->setText(QApplication::translate("MainWindow", "\330\247\330\250\330\255\330\253 \330\271\331\206", 0));
        label_2->setText(QApplication::translate("MainWindow", "\331\210\330\247\330\263\330\252\330\250\330\257\331\204 \330\250\331\207", 0));
        btnFindPrev->setText(QApplication::translate("MainWindow", ">", 0));
        btnFindPrev->setShortcut(QApplication::translate("MainWindow", "Shift+F3", 0));
        btnFindNext->setText(QApplication::translate("MainWindow", "<", 0));
        btnFindNext->setShortcut(QApplication::translate("MainWindow", "F3", 0));
        btnReplacePrev->setText(QApplication::translate("MainWindow", ">", 0));
        btnReplaceNext->setText(QApplication::translate("MainWindow", "<", 0));
        lblFindStatus->setText(QString());
        functionNavigationToolbar->setWindowTitle(QApplication::translate("MainWindow", "toolBar", 0));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
